# .github/dependabot.yml
version: 2
updates:
  # DevContainer の依存関係チェック
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: "weekly"

  # npm パッケージの依存関係チェック
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    versioning-strategy: auto

  # GitHub Actions の依存関係チェック
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Docker イメージの依存関係チェック
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"

