version: '3.8'

services:
  app:
    build: 
      context: ..
      dockerfile: docker/development.Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ..:/app
    environment:
      - NODE_ENV=development 