name: Deploy to Production

on:
  push:
    branches:
      - main
  workflow_dispatch:  # 手動実行も可能に

env:
  AWS_REGION: ap-northeast-1
  ECR_REPOSITORY: aws-fargate-express-01-repository
  ECS_CLUSTER: aws-fargate-express-01-cluster
  ECS_SERVICE: aws-fargate-express-01-service
  ECS_TASK_FAMILY: aws-fargate-express-01-task
  CONTAINER_NAME: fargate-express
  IMAGE_TAG: ${{ github.sha }}  # コミットハッシュをタグとして使用

jobs:
  deploy:
    name: Deploy to ECS
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          mask-aws-account-id: true

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/production.Dockerfile
          push: true
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
            ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Download task definition
        id: download-taskdef
        run: |
          echo "Fetching current task definition..."
          if ! aws ecs describe-task-definition \
            --task-definition ${{ env.ECS_TASK_FAMILY }} \
            --query 'taskDefinition | {
              family: family,
              networkMode: networkMode,
              requiresCompatibilities: requiresCompatibilities,
              cpu: cpu,
              memory: memory,
              containerDefinitions: containerDefinitions,
              executionRoleArn: executionRoleArn,
              taskRoleArn: taskRoleArn
            }' > task-definition.json; then
            echo "Failed to fetch task definition. Creating a new one..."
            echo '{
              "family": "${{ env.ECS_TASK_FAMILY }}",
              "networkMode": "awsvpc",
              "requiresCompatibilities": ["FARGATE"],
              "cpu": "256",
              "memory": "512",
              "executionRoleArn": "arn:aws:iam::${{ steps.login-ecr.outputs.account }}:role/ecsTaskExecutionRole",
              "containerDefinitions": [{
                "name": "${{ env.CONTAINER_NAME }}",
                "image": "${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:latest",
                "portMappings": [{
                  "containerPort": 8080,
                  "protocol": "tcp"
                }],
                "essential": true,
                "logConfiguration": {
                  "logDriver": "awslogs",
                  "options": {
                    "awslogs-group": "/ecs/${{ env.ECS_TASK_FAMILY }}",
                    "awslogs-region": "${{ env.AWS_REGION }}",
                    "awslogs-stream-prefix": "ecs"
                  }
                }
              }]
            }' > task-definition.json
          fi
          cat task-definition.json

      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: ${{ env.CONTAINER_NAME }}
          image: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}

      - name: Deploy to Amazon ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true
          force-new-deployment: true

      - name: Post-deployment check
        run: |
          echo "Waiting for service to stabilize..."
          aws ecs wait services-stable \
            --cluster ${{ env.ECS_CLUSTER }} \
            --services ${{ env.ECS_SERVICE }}
          
          # サービスの状態を確認
          aws ecs describe-services \
            --cluster ${{ env.ECS_CLUSTER }} \
            --services ${{ env.ECS_SERVICE }} \
            --query 'services[0].{runningCount:runningCount,desiredCount:desiredCount,status:status}'