name: Deploy to Staging

on:
  push:
    branches:
      - develop

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.LIGHTSAIL_IP }} >> ~/.ssh/known_hosts

      - name: Deploy and Start Application
        run: |
          # Deploy to correct path
          ssh -i ~/.ssh/id_rsa ec2-user@${{ secrets.LIGHTSAIL_IP }} 'mkdir -p /home/ec2-user/dev/infra-devcontainer-aws-cdk-cicd-nodejs'
          scp -i ~/.ssh/id_rsa -r ./* ec2-user@${{ secrets.LIGHTSAIL_IP }}:/home/ec2-user/dev/infra-devcontainer-aws-cdk-cicd-nodejs/
          
          # Install dependencies and start application in staging mode
          ssh -i ~/.ssh/id_rsa ec2-user@${{ secrets.LIGHTSAIL_IP }} 'cd /home/ec2-user/dev/infra-devcontainer-aws-cdk-cicd-nodejs && \
            npm install && \
            npm run pm2-stop || true && \
            npm run staging'
